spring.application.name=weld-track-api


spring.datasource.url=jdbc:postgresql://localhost:5432/weldtrack
spring.datasource.username=weldtrack_user
spring.datasource.password=weldtrack123

spring.jpa.hibernate.ddl-auto=create-drop

spring.sql.init.mode=never