spring.datasource.url=jdbc:postgresql://localhost:5432/weldtrack
spring.datasource.username=weldtrack_user
spring.datasource.password=weldtrack123

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update