CREATE table IF NOT EXISTS equipamentos (
    id INT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    nome varchar (200),
    tipo varchar (200),
    valor_min INT,
    valor_max INT
);

INSERT INTO equipamentos (nome, tipo, valor_min, valor_max)
VALUES  ('Soldadora MMA inverter', 'solda eletrodo', 100, 600),
        ('Soldadora MIG/MAG invereter', 'solda a fio', 200, 800),
        ('Soldadora TIG AC/DC', 'solda de precição com eletrodo de tungénio', 300, 1500),
        ('Solda com Maçarico', 'solda e corte com chama', 150, 600);

